// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpareParts.Data.AppDbContext;

namespace SpareParts.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpareParts.Data.Model.account", b =>
                {
                    b.Property<Guid>("new_account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("new_account_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_account_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_account_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("new_account_role")
                        .HasColumnType("int");

                    b.Property<Guid>("new_department_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("new_department_id1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("new_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("new_account_id");

                    b.HasIndex("new_department_id1");

                    b.ToTable("new_account");
                });

            modelBuilder.Entity("SpareParts.Data.Model.department", b =>
                {
                    b.Property<Guid>("new_department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("new_account_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("new_department_des")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_department_func")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_department_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("new_department_id");

                    b.ToTable("new_department");
                });

            modelBuilder.Entity("SpareParts.Data.Model.account", b =>
                {
                    b.HasOne("SpareParts.Data.Model.department", "new_department")
                        .WithMany("new_account")
                        .HasForeignKey("new_department_id1");

                    b.Navigation("new_department");
                });

            modelBuilder.Entity("SpareParts.Data.Model.department", b =>
                {
                    b.Navigation("new_account");
                });
#pragma warning restore 612, 618
        }
    }
}
